# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
# Before updating anything please sync-up with #ruby-style-guide on Slack.
inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/**/*'
    - '*.gemspec'
    - 'Guardfile'
    - 'Gemfile'
    - 'bin/**/*'
    - 'spec/**/*'
    - '.pryrc'

Security/Open:
  Enabled: false