platform_type: Magento
object_types:
  customer:
    record_key: email
    key_required: true
    pipeline_stages:
      - TopLevelAttributes
export_configuration:
  soap:
    username: 'something'
  store_id: 1
